theme: minima 
title: What are you doing to that cow!
author: Whitter11
email: your-email@domain.com
description:
Open discussions about the Wait What?! moments
All curiously observant and stoners welcome, we do not discriminate here, if you can think weird you can talk weird with me
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
